<x-app-layout>
    @include('welcome.partials._header')
    @include('welcome.partials._hero')
    @include('welcome.partials._featured')
    @include('welcome.partials._sale')
    @include('welcome.partials._subscribe')
    @include('welcome.partials._categories')
    @include('welcome.partials._footer')
</x-app-layout>
